### ISSUE TITLE
开启音乐功能则中文目录无法跳转

### ISSUE THREAD

**Issue by ImmerTry** [huweihuang/hexo-theme-huweihuang#1]
是不是某些代码上没实现

**Comment by huweihuang** [comment]
具体参见issue：https://github.com/MoePlayer/APlayer/issues/242

因为之前加了音乐的功能，导致右侧目录中文标题跳转异常，但英文标题跳转是正常的，你可以在根目录下的`_config.yml`中把音乐功能关掉，`mtingjs`的值改为`false`。

例如：
```
metingjs: false
data-id: 2423410161
data-server: netease  
data-type: playlist
data-fixed: true
```

**Comment by DoyoudoLove** [comment]
好的，我试一下

**Comment by nqmysb** [comment]
我发现使用IE浏览器是可以跳转 chrome则不会跳转

**Comment by nqmysb** [comment]
toc 锚点失效bug 已经修复了  [https://github.com/nqmysb/hexo-theme-huweihuang/commit/9896728accbda1f880c1216f443a5251d1b072f5](url)

**Comment by huweihuang** [comment]
已在 https://github.com/huweihuang/hexo-theme-huweihuang/pull/32 中修复，感谢 @nqmysb 提交的代码。
