### ISSUE TITLE
为什么不把node_modules忽略掉？

### ISSUE THREAD

**Issue by ovensi** [huweihuang/hexo-theme-huweihuang#23]
为什么不把node_modules忽略掉？node_modules明明可以通过package.json自行下载的。不忽略clone非常慢。

**Comment by huweihuang** [comment]
参考这个issue：https://github.com/huweihuang/hexo-theme-huweihuang/issues/5，待后续这个修复好就可以把node_modules包去掉了。因为暂时改了node_modules 依赖包的部分代码。

**Comment by huweihuang** [comment]
fix by:https://github.com/huweihuang/hexo-theme-huweihuang/commit/542876d7ba3a19558e8225cfaa5e9712ca3ffa86
