### ISSUE TITLE
上下滑动不顺畅

### ISSUE THREAD

**Issue by charliewong001** [huweihuang/hexo-theme-huweihuang#27]
如题，阅读文章的时候，上下滑动滚动条会出现 bug，上下滑动时会划不动，右侧滚动条位置不对。有人遇到过吗？

**Comment by nqmysb** [comment]
> 如题，阅读文章的时候，上下滑动滚动条会出现 bug，上下滑动时会划不动，右侧滚动条位置不对。有人遇到过吗？

应该是某些组件冲突造成的，可以参考我的PR https://github.com/huweihuang/hexo-theme-huweihuang/pull/16

**Comment by charliewong001** [comment]
将 layout 下 post.ejs 中的 article 标签整个注释掉就好了...
