### ISSUE TITLE
Make this repo more pure

### ISSUE THREAD

**Issue by Liaomessi** [huweihuang/hexo-theme-huweihuang#46]
Maybe, this hexo-theme repo could be more pure.
You can remove some useless code in remote repo, such as node_modules. It's too large to download.
In my point of view, the only folder need exist in this repo is 'themes'.
Think you.

**Comment by huweihuang** [comment]
ref:https://github.com/huweihuang/hexo-theme-huweihuang/issues/23 , already fixed
