### ISSUE TITLE
重新npm install会导致文章右边的目录链接 #undefined

### ISSUE THREAD

**Issue by nqmysb** [huweihuang/hexo-theme-huweihuang#5]
你好 我用了你的主题，然后文章右边的目录链接会失效 ，访问链接hash后面的值为undefined ，如：/article/source-analysis/source-analysis1/#undefined ，标题目录不是中文，找了好久不知道什么原因

**Comment by Sciroccogti** [comment]
#1

**Comment by nqmysb** [comment]
你好 谢谢，这个我了解，但是我发现的这个问题是我把node_moudles删了，然后重新根据package.json去npm install 发现就会出现我上面描述的问题，无论是中文还是英文右边的标题都链接都会失效，是否是package.json没有--save一些依赖包的缘故? 导致重新install右边的目录链接就会出现undefined的问题？

**Comment by huweihuang** [comment]
@nqmysb 参考这个issue：https://github.com/YenYuHsuan/hexo-theme-beantech/issues/11，是npm install 其中一个更新的包的问题，目前暂时我是用issue中提到的方法，注释掉包的更新，但不是根本的解决方法，如果有兴趣，你也可以修复下这个问题，然后提一个PR到我这边。

**Comment by Zirpon** [comment]
中文章节标题  点击文章右侧的侧边栏，不跳转

**Comment by nqmysb** [comment]
可以参考我的bug修复提交，解决了这个问题

**Comment by Zirpon** [comment]
看到了 感谢 回家后试试 整了一天了 😂😂

**Comment by Zirpon** [comment]
中文标题 跳转: @nqmysb 的 [commit](https://github.com/nqmysb/hexo-theme-huweihuang/commit/9896728accbda1f880c1216f443a5251d1b072f5)

**Comment by huweihuang** [comment]
fix by:https://github.com/huweihuang/hexo-theme-huweihuang/commit/542876d7ba3a19558e8225cfaa5e9712ca3ffa86
