### ISSUE TITLE
添加文章可置顶功能

### ISSUE THREAD

**Issue by huweihuang** [huweihuang/hexo-theme-huweihuang#9]

**Comment by nqmysb** [comment]
参考这个commit 
https://github.com/huweihuang/hexo-theme-huweihuang/pull/16/commits/9a04b24fce330c8d5ec716ae3ac565aea9b30a05
只要在post页添加 top属性即可  top值越大，排在最上面

**Comment by nqmysb** [comment]
参考效果 ：https://github.com/huweihuang/hexo-theme-huweihuang/pull/16#issuecomment-472404121

**Comment by huweihuang** [comment]
@nqmysb 感谢提交该功能代码，由于你这边提交的pr https://github.com/huweihuang/hexo-theme-huweihuang/pull/16 中有部分内容不方便merge，因此我使用 hexo-generator-index-plus 这个第三方包的方式和你的代码，重新提了一个pr ，参考 https://github.com/huweihuang/hexo-theme-huweihuang/pull/33，建议后续如果有bug fix 和feature 可以单独提一个pr，方便review和merge。

**Comment by stevenjoezhang** [comment]
Hexo 已实现文章置顶参数： hexojs/hexo-generator-index#51
